apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: {{ include "thingsboard-pe.namespace" . }}
  labels:
    {{- include "thingsboard-pe.labels" . | nindent 4 }}
    app: cassandra
spec:
  clusterIP: None
  ports:
    - port: 9042
      targetPort: 9042
      name: cql
    - port: 7000
      targetPort: 7000
      name: intra-node
    - port: 7001
      targetPort: 7001
      name: tls-intra-node
  selector:
    app: cassandra