apiVersion: v1
kind: ConfigMap
metadata:
  name: coap-pem-configmap
  namespace: {{ .Values.global.namespace }}
data:
  server.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB9TCCAZsCFFGkN9f4vnxw/nPIhOCvI1tJbvmsMAoGCCqGSM49BAMCMH0xCzAJ
    BgNVBAYTAlpBMRUwEwYDVQQIDAxXZXN0ZXJuIENhcGUxEjAQBgNVBAcMCUNhcGUg
    VG93bjESMBAGA1UECgwJU3RhZ2VaZXJvMQ0wCwYDVQQLDARDb0FQMSAwHgYDVQQD
    DBdjb2FwLnFhLnN0YWdlemVyby5jby56YTAeFw0yNDEyMDIxNjU2MjFaFw0yNTEy
    MDIxNjU2MjFaMH0xCzAJBgNVBAYTAlpBMRUwEwYDVQQIDAxXZXN0ZXJuIENhcGUx
    EjAQBgNVBAcMCUNhcGUgVG93bjESMBAGA1UECgwJU3RhZ2VaZXJvMQ0wCwYDVQQL
    DARDb0FQMSAwHgYDVQQDDBdjb2FwLnFhLnN0YWdlemVyby5jby56YTBZMBMGByqG
    SM49AgEGCCqGSM49AwEHA0IABNFTlCwq4AbdEQiHztUj0C4SkiQf418fXuGuGqFZ
    ufH9gX2Q8PzGvjbhpYpJDIA7f7SMR1CRh15A3q2tFT8FTbwwCgYIKoZIzj0EAwID
    SAAwRQIget7ssyB6DPBp4bK43RG1G3eOCH5Jrna9TNXJRBZLt4ECIQD6Dplf75yi
    BnW1JVbY2Glq4ClpqXhpBRcCeZVIkAGxPg==
    -----END CERTIFICATE-----
  server_key.pem: |
    -----BEGIN EC PARAMETERS-----
    BggqhkjOPQMBBw==
    -----END EC PARAMETERS-----
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEICL3QXJkBZz0Ew6smaY4gKS3W+i7kcXGkcWANslQb6w2oAoGCCqGSM49
    AwEHoUQDQgAE0VOULCrgBt0RCIfO1SPQLhKSJB/jXx9e4a4aoVm58f2BfZDw/Ma+
    NuGlikkMgDt/tIxHUJGHXkDera0VPwVNvA==
    -----END EC PRIVATE KEY-----
